In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("..\\datasets\\crime\\crime_delhi.csv")
df2 = pd.read_csv("..\\datasets\\crime\\crime_delhi_filtered.csv")

In [21]:
df2.columns

Index(['nm_pol', 'murder', 'rape', 'robbery', 'theft', 'assualt murders',
       'sexual harassement', 'year', 'district'],
      dtype='str')

In [22]:
df.columns

Index(['nm_pol', 'murder', 'rape', 'gangrape', 'robbery', 'theft',
       'assualt murders', 'sexual harassement', 'totalarea', 'totalcrime',
       'long', 'lat', 'crime/area', 'area'],
      dtype='str')

In [23]:
df = df.drop(columns=['murder', 'rape', 'robbery', 'theft', 'assualt murders','sexual harassement', 'long', 'lat', 'crime/area'])

In [24]:
df = df.merge(
    df2,
    left_on="nm_pol", 
    right_on="nm_pol",
    how="right"
)

In [25]:
df['district'].unique()

<StringArray>
[ 'South-East',      'Dwarka',       'South',     'Central',  'North-West',
       'North',      'Rohini',        'West',  'South-West',   'New Delhi',
        'East',       'Outer',    'Shahdara', 'Outer-North',  'North-East']
Length: 15, dtype: str

In [26]:
df.sample(10)

,nm_pol,gangrape,totalarea,totalcrime,area,murder,rape,robbery,theft,assualt murders,sexual harassement,year,district
295,karol bagh,0,1.643642e+06,210,1.643642,4,24,10,437,6,4,2019,Central
315,seemapuri,0,4.731869e+06,307,4.731869,1,2,4,890,10,6,2019,Shahdara
231,geeta colony,0,1.021961e+06,292,1.021961,3,6,2,860,6,6,2019,Shahdara
116,kirti nagar,2,1.511976e+06,274,1.511976,5,17,5,499,18,5,2018,West
100,paschim vihar,0,3.794664e+06,632,3.794664,2,13,16,1293,10,19,2018,West
20,chanakyapuri,2,1.099345e+07,723,10.993453,1,9,13,1595,16,2,2018,New Delhi
90,vikaspuri,1,1.247662e+06,232,1.247662,2,4,5,501,6,1,2018,West
156,mundka,0,4.858236e+07,270,48.582359,1,5,4,587,9,2,2018,Outer
155,harsh vihar,0,2.572205e+06,529,2.572205,2,9,8,1158,14,4,2018,Shahdara
92,defence colony,1,2.480277e+06,227,2.480277,3,15,8,388,13,6,2018,South-East

In [27]:
df

,nm_pol,gangrape,totalarea,totalcrime,area,murder,rape,robbery,theft,assualt murders,sexual harassement,year,district
0,chitranjan park (cr park),1,2659329.537,512,2.659330,2,7,12,1086,15,4,2018,South-East
1,dabri,0,3401013.428,397,3.401013,7,27,26,590,21,10,2018,Dwarka
2,malviya nagar,1,1379853.572,837,1.379854,3,28,11,1706,50,9,2018,South
3,chandni mahal,1,5570696.132,588,5.570696,1,9,8,1300,15,4,2018,Central
4,model town,1,2689157.085,466,2.689157,0,5,15,966,7,9,2018,North-West
...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,gtb enclave,0,2874304.374,114,2.874304,1,1,3,291,4,4,2019,Shahdara
328,new usmanpur,1,3093393.387,613,3.093393,0,9,3,1963,6,3,2019,North-East
329,sonia vihar,1,4453887.398,407,4.453887,5,26,7,1016,29,4,2019,North-East
330,karawal nagar,2,2937546.578,410,2.937547,6,17,7,1131,13,4,2019,North-East
331,gokalpuri,2,1566343.791,365,1.566344,2,8,6,1036,13,4,2019,North-East

In [28]:
if "crime/area" not in df.columns:
    df["crime_per_area"] = df["totalcrime"] / (df["area"] + 1e-8)
else:
    df["crime_per_area"] = df["crime/area"]

In [29]:
df.head()

,nm_pol,gangrape,totalarea,totalcrime,area,murder,rape,robbery,theft,assualt murders,sexual harassement,year,district,crime_per_area
0,chitranjan park (cr park),1,2659329.537,512,2.659330,2,7,12,1086,15,4,2018,South-East,192.529730
1,dabri,0,3401013.428,397,3.401013,7,27,26,590,21,10,2018,Dwarka,116.729912
2,malviya nagar,1,1379853.572,837,1.379854,3,28,11,1706,50,9,2018,South,606.586098
3,chandni mahal,1,5570696.132,588,5.570696,1,9,8,1300,15,4,2018,Central,105.552338
4,model town,1,2689157.085,466,2.689157,0,5,15,966,7,9,2018,North-West,173.288500

In [30]:
df["nm_pol"] = df["nm_pol"].str.strip().str.upper()

In [31]:
len(df['nm_pol'].unique())

157

In [32]:
df.head()

,nm_pol,gangrape,totalarea,totalcrime,area,murder,rape,robbery,theft,assualt murders,sexual harassement,year,district,crime_per_area
0,CHITRANJAN PARK (CR PARK),1,2659329.537,512,2.659330,2,7,12,1086,15,4,2018,South-East,192.529730
1,DABRI,0,3401013.428,397,3.401013,7,27,26,590,21,10,2018,Dwarka,116.729912
2,MALVIYA NAGAR,1,1379853.572,837,1.379854,3,28,11,1706,50,9,2018,South,606.586098
3,CHANDNI MAHAL,1,5570696.132,588,5.570696,1,9,8,1300,15,4,2018,Central,105.552338
4,MODEL TOWN,1,2689157.085,466,2.689157,0,5,15,966,7,9,2018,North-West,173.288500

In [33]:
def convert_district(cell_value, mapping_dic):
    return mapping_dic.get(cell_value, cell_value)

dic = {
    "Shahdara": "EAST",
    "Outer-North": "OUTER",
    "Rohini": "NORTH WEST"
}

df['district'] = df['district'].apply(lambda x: convert_district(x, dic))
df['district'] = df['district'].str.upper()

In [34]:
df['district'].unique()

<StringArray>
['SOUTH-EAST',     'DWARKA',      'SOUTH',    'CENTRAL', 'NORTH-WEST',
      'NORTH', 'NORTH WEST',       'WEST', 'SOUTH-WEST',  'NEW DELHI',
       'EAST',      'OUTER', 'NORTH-EAST']
Length: 13, dtype: str

In [35]:
df.to_csv("..\\datasets\\crime/crime_processed.csv", index=False)